# Generated by Django 5.2.11 on 2026-03-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_classroom_teacher_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='subject',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Science', 'Science'), ('English', 'English'), ('Hindi', 'Hindi'), ('SST', 'Social Studies')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Science', 'Science'), ('English', 'English'), ('Hindi', 'Hindi'), ('SST', 'Social Studies')], max_length=20),
        ),
    ]
